# Ace of Shades Server Settings

# Changes to these settings take effect only after restarting the server.


# The port that this server uses for TCP and UDP communication.
port: 8035
# The maximum number of players that can be connected at once.
max-players: 32
# How many times per second should physics updates be calculated.
# WARNING: Changing this has a major impact on server performance.
ticks-per-second: 120


# Information for the public server registry. Ignore this unless you want your server to be displayed publicly.
registry-settings:
  # Set this to true to allow other players to see this server and join it.
  discoverable: false
  # The URI which points to the registry server. This is only used if discoverable is true.
  registry-uri: "http://37.97.207.39:25566"
  # How often to send status updates to the registry server, in seconds.
  update-interval: 30
  # The name of this server.
  name: "Testing Server"
  # The address that clients can use to connect to this server.
  address: "localhost:8035"
  # A short description of this server.
  description: "A simple testing server for development."
  # Location of this server, to help players choose servers near to them.
  location: "Earth"
  # Note: To set an icon for this server, add an "icon.png" image to the server's directory (where the settings are).
  # The icon MUST be 64x64 pixels in size.


# Settings that control player behavior.
player-settings:
  # Walking speed, in meters per second.
  speed: 10
  # Sprinting speed, in meters per second.
  sprint-speed: 18
  # Sneaking speed, in meters per second.
  sneak-speed: 5
  # Acceleration when player starts moving or changes direction, in m/s^2.
  acceleration: 60
  # Deceleration when player stops moving, in m/s^2.
  deceleration: 30
  # The radius of the player.
  radius: 0.5
  # How many seconds a player must wait before resupplying again.
  resupply-cooldown: 30
  # The maximum health of players.
  max-health: 100
  # How quickly players regenerate health, in points per second. Set to 0 to disable regeneration.
  health-regen-rate: 1.0
  # How much sneaking affects gun inaccuracy. Values less than 0 increase inaccuracy, and greater than 0 decrease inaccuracy.
  sneak-accuracy-modifier: 0.5
  # How much sprinting affects gun inaccuracy. Values less than 0 increase inaccuracy, and greater than 0 decrease inaccuracy.
  sprint-accuracy-modifier: 1.5
  # Should be the name of one of the guns defined in "gun-settings".
  default-gun: M1 Garand


# Settings for team mechanics.
team-settings:
  # The radius of team spawn points, in meters.
  spawn-point-radius: 3
  # The radius of team resupply points, in meters.
  supply-point-radius: 2
  # Whether friendly fire is enabled. If enabled, players can kill teammates.
  friendly-fire: false


# The list of available guns are defined in this list.
gun-settings:
  - name: AK-47 # The name of the gun.
    category: SMG # The category of gun. This affects sounds base functionality.
    color: "#2e2b26" # The color of the gun in the player's hand.
    max-clip-count: 4 # The maximum number of clips which a player can hold for this gun.
    clip-size: 30 # The number of rounds in each clip.
    bullets-per-round: 1 # The number of bullets spawned for each round fired.
    inaccuracy: 0.10 # The inaccuracy of the gun, or rather deviation. Increase this to decrease inaccuracy.
    shot-cooldown-time: 0.05 # How many seconds to wait after shooting before you can shoot again.
    reload-time: 1.2 # How many seconds to wait while reloading.
    bullet-speed: 90 # How fast the bullets from this gun fly, in meters per second.
    base-damage: 40 # The amount of damage that bullets from this gun do, assuming a direct hit.
    recoil: 3 # How much the player is pushed back after each shot, in meters per second.

  - name: Nerf Blaster
    category: SMG
    color: "#ffc619"
    max-clip-count: 5
    clip-size: 16
    bullets-per-round: 1
    inaccuracy: 0.20
    shot-cooldown-time: 0.25
    reload-time: 1.0
    bullet-speed: 40
    base-damage: 1
    recoil: 0.25

  - name: Nerf Infiniblaster
    category: MACHINE
    color: "#b52bff"
    max-clip-count: 3
    clip-size: 500
    bullets-per-round: 1
    inaccuracy: 0.10
    shot-cooldown-time: 0.04
    reload-time: 3
    bullet-speed: 60
    base-damage: 1
    recoil: 0.25

  - name: M-249
    category: MACHINE
    color: "#001942"
    max-clip-count: 3
    clip-size: 100
    bullets-per-round: 1
    inaccuracy: 0.08
    shot-cooldown-time: 0.03
    reload-time: 3.5
    bullet-speed: 80
    base-damage: 35
    recoil: 2

  - name: M1 Garand
    category: RIFLE
    color: "#452d06"
    max-clip-count: 10
    clip-size: 8
    bullets-per-round: 1
    inaccuracy: 0.02
    shot-cooldown-time: 0.75
    reload-time: 0.75
    bullet-speed: 150
    base-damage: 100
    recoil: 20

  - name: Winchester
    category: SHOTGUN
    color: "#1a1205"
    max-clip-count: 8
    clip-size: 6
    bullets-per-round: 5
    inaccuracy: 0.15
    shot-cooldown-time: 0.5
    reload-time: 2.0
    bullet-speed: 75
    base-damage: 80
    recoil: 40